apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: my-app
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

